#!/bin/bash
read -p "This will destroy any existing databases. Do you want to continue? (y/n)?" CONT
if [ "$CONT" != "y" ]; then
  exit
fi
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $DRUPAL_DB_HOST -e "DROP DATABASE IF EXISTS $DRUPAL_DB_NAME; CREATE DATABASE $DRUPAL_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $DRUPAL_DB_HOST -e "GRANT ALL PRIVILEGES ON $DRUPAL_DB_NAME.* TO '$DRUPAL_DB_USER' IDENTIFIED BY '$DRUPAL_DB_PASS'"
drush -r /var/www/html/ site-install -y
drush dis overlay -y