#!/usr/bin/env php
<?php
if (count($argv) != 3) {
    die('Need exactly two arguments: search and replace URL');
}

$prodUrl = $argv[1];
$devUrl = $argv[2];

searchAndReplace($prodUrl, $devUrl);

function searchAndReplace($find, $replace)
{
    foreach (columns() as $c) {
        $table = $c['table'];
        $col = $c['col'];
        $type = $c['type'];
        echo "Checking {$table}.{$col}...\n";
        $selectResult = db()->query("SELECT `{$col}` FROM `{$table}` WHERE `{$col}` LIKE '%{$find}%'");
        $selectCount = $selectResult->rowCount();
        echo "Found {$selectCount} instances of '{$find}' in {$table}.{$col}.\n";
        if ($selectCount) {
            $colLength = 0;
            if (preg_match('/varchar\((\d+)\)/', $type, $matches)) {
                $colLength = $matches[1];
            }
            if ($colLength) {
                $function = "SUBSTRING(REPLACE(`{$col}`, '{$find}', '{$replace}'), 1, {$colLength})";
            }
            else {
                $function = "REPLACE(`{$col}`, '{$find}', '{$replace}')";
            }
            $updateQuery = "UPDATE `{$table}`
                SET `{$col}`= {$function}
                WHERE `{$col}` LIKE '%{$find}%'";
            try {
                $updateResult = db()->query($updateQuery);
                $updateCount = $updateResult->rowCount();
                echo "Updated {$updateCount} rows in {$table}.{$col}.\n";
            }
            catch (\Throwable $th) {
                echo "Error running '$updateQuery'.\n";
            }
        }
    }
}

function columns()
{
    $result = [];
    foreach (tables() as $table) {
        foreach (db()->query("DESCRIBE {$table}") as $col) {
            $result[] = ['table' => $table, 'col' => $col['Field'], 'type' => $col['Type']];
        }
    }
    return $result;
}

function tables()
{
    $result = [];
    foreach (db()->query('SHOW TABLES') as $row) {
        $result[] = $row[0];
    }
    return $result;
}

function db()
{
    static $db;
    if (!$db) {
        $db = new PDO(
            'mysql:host=' . getenv('WORDPRESS_DB_HOST') . ';dbname=' . getenv('WORDPRESS_DB_NAME'),
            getenv('WORDPRESS_DB_USER'),
            getenv('WORDPRESS_DB_PASS')
        );
    }
    return $db;
}
