#!/bin/bash

pushd /var/www/html

  chmod u+w .
  for FILE in wp-config.php civicrm.settings.php .htaccess; do
    if test -f "$FILE"; then
      echo chmod u+w $FILE
      chmod u+w $FILE
    fi
    cp /usr/local/etc/civicrm/$FILE .
    echo cp /usr/local/etc/civicrm/$FILE .
    chmod a-wx $FILE
  done
  rm -rf files
  mkdir files
  chmod u-w .

popd

mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $WORDPRESS_DB_HOST -e "DROP DATABASE IF EXISTS $WORDPRESS_DB_NAME; CREATE DATABASE $WORDPRESS_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $WORDPRESS_DB_HOST -e "GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER' IDENTIFIED BY '$WORDPRESS_DB_PASS'"

