#!/bin/bash
read -p "This will initialise CiviCRM and WordPress ready for install, destroying any existing data. Do you want to continue? (y/n)?" CONT
if [ "$CONT" != "y" ]; then
  exit
fi

cp /usr/local/etc/civicrm/wp-config /var/www/html
cp /usr/local/etc/civicrm/civicrm.settings.php /var/www/html
cp /usr/local/etc/civicrm/.htaccess /var/www/html
chmod a-rwx,u+r /var/www/html/wp-config.php
chmod a-rwx,u+r /var/www/html/civicrm.settings.php
chmod a-rwx,u+r /var/www/html/.htaccess

mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $WORDPRESS_DB_HOST -e "DROP DATABASE IF EXISTS $WORDPRESS_DB_NAME; CREATE DATABASE $WORDPRESS_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $WORDPRESS_DB_HOST -e "GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER' IDENTIFIED BY '$WORDPRESS_DB_PASS'"

