#!/bin/bash

pushd /var/www/html

  chmod u+w .
  for FILE in wp-config.php civicrm.settings.php .htaccess; do
    if test -f "$FILE"; then
      echo chmod u+w $FILE
      chmod u+w $FILE
    fi
    cp /usr/local/etc/civicrm/$FILE .
    echo cp /usr/local/etc/civicrm/$FILE .
    chmod a-wx $FILE
  done
  rm -rf files
  mkdir files
  chmod u-w .

popd
