#!/bin/bash
read -p "This will destroy any existing databases. Do you want to continue? (y/n)?" CONT
if [ "$CONT" != "y" ]; then
  exit
fi

cp /usr/local/etc/civicrm/settings.php /var/www/html
cp /usr/local/etc/civicrm/civicrm.settings.php /var/www/html
chmod a-rwx,u+r /var/www/html/settings.php
chmod a-rwx,u+r /var/www/html/civicrm.settings.php


mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $BACKDROP_DB_HOST -e "DROP DATABASE IF EXISTS $BACKDROP_DB_NAME; CREATE DATABASE $BACKDROP_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $BACKDROP_DB_HOST -e "GRANT ALL PRIVILEGES ON $BACKDROP_DB_NAME.* TO '$BACKDROP_DB_USER' IDENTIFIED BY '$BACKDROP_DB_PASS'"

