#!/bin/bash
read -p "This will initialise CiviCRM and Backdrop ready for installation or for loading an existing state. It will destroy any existing data. Do you want to continue? (y/n)?" CONT
if [ "$CONT" != "y" ]; then
  exit
fi

chmod u+w /var/www/html{,/settings.php,/civicrm.settings.php}
cp /usr/local/etc/civicrm/settings.php /var/www/html
cp /usr/local/etc/civicrm/civicrm.settings.php /var/www/html
chmod o-rwx,u-wx /var/www/html/settings.php
chmod o-rwx,u-wx /var/www/html/civicrm.settings.php
rm -rf /var/www/html/files
mkdir /var/www/html/files
chmod u-w /var/www/html

mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $BACKDROP_DB_HOST -e "DROP DATABASE IF EXISTS $BACKDROP_DB_NAME; CREATE DATABASE $BACKDROP_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $BACKDROP_DB_HOST -e "GRANT ALL PRIVILEGES ON $BACKDROP_DB_NAME.* TO '$BACKDROP_DB_USER' IDENTIFIED BY '$BACKDROP_DB_PASS'"

