#!/bin/bash
set -xe

read -p "This will destroy any existing databases. Do you want to continue? (y/n)?" CONT
if [ "$CONT" != "y" ]; then
  exit
fi
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $WORDPRESS_DB_HOST -e "DROP DATABASE IF EXISTS $WORDPRESS_DB_NAME; CREATE DATABASE $WORDPRESS_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $WORDPRESS_DB_HOST -e "GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER' IDENTIFIED BY '$WORDPRESS_DB_PASS'"

wp core install --url=$BASE_URL --title=civicrm-on-wordpress --admin_user=admin --admin_email=admin@example.com
cv core:install --settings-path=/var/www/html/civicrm.settings.php --keep --db=mysql://$CIVICRM_DB_USER:$CIVICRM_DB_PASS@$CIVICRM_DB_HOST:$CIVICRM_DB_PORT/$CIVICRM_DB_NAME
wp plugin activate civicrm
