#!/usr/bin/env php
<?php
$dbEnvs = [
  'CIVICRM_DSN',
  'CIVICRM_UF_DSN'
];
$rootPassword = getenv('MYSQL_ROOT_PASSWORD');
foreach($dbEnvs as $dbEnv){
  $url = parse_url(getenv($dbEnv));
  var_dump($url);
  $host = $url['host'];
  $password = $url['pass'];
  $db = substr($url['path'], 1);
  echo "mysql -h $host -u root -p$rootPassword -e 'CREATE DATABASE IF NOT EXISTS $db';\n";
  echo "$password;\n";
}
