#!/bin/bash
read -p "This will install CiviCRM on Backdrop, destroying any existing data. Do you want to continue? (y/n)?" CONT
if [ "$CONT" != "y" ]; then
  exit
fi

cd /var/www/html

# Prepare for Backdrop install
chmod u+w .
rm -f settings.php
touch settings.php

# Run Backdrop install script
drush backdrop-site-install --db-url="mysql://$BACKDROP_DB_NAME:$BACKDROP_DB_PASS@$BACKDROP_DB_HOST/$BACKDROP_DB_NAME"

# Prepare for CiviCRM install
rm -f /var/www/html/civicrm.settings.php

# Run CiviCRM install script
cv core:install --db=mysql://$CIVICRM_DB_USER:$CIVICRM_DB_PASS@$CIVICRM_DB_HOST:$CIVICRM_DB_PORT/$CIVICRM_DB_NAME --cms-base-url=$BASE_URL


# cp /usr/local/etc/civicrm/settings.php /var/www/html
# cp /usr/local/etc/civicrm/civicrm.settings.php /var/www/html
chmod a-w /var/www/html /var/www/html/settings.php /var/www/html/civicrm.settings.php

