#!/bin/sh
set -e

CONTAINER_IP=`/sbin/ip route|awk '/default/ { print $3 }'`

# sendmail via smtp
cat << EOF > /etc/msmtprc
host $SMTP_HOST
auto_from on
maildomain $SMTP_MAILDOMAIN
EOF

# my.cnf config
cat << EOF > /home/civicrm/.my.cnf
[client]
user=root
password=$MYSQL_ROOT_PASSWORD
host=$CIVICRM_DB_HOST
EOF

echo $CONTAINER_IP $DOMAIN >> /etc/hosts


if [ "$DEBUG" = "ON" ]; then
	cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
	XDEBUG_REMOTE_HOST=`/sbin/ip route|awk '/default/ { print $3 }'`
    cat << EOF > /usr/local/etc/php/conf.d/debug.ini
zend_extension=xdebug.so
xdebug.show_error_trace=1
xdebug.remote_enable=1
xdebug.profiler_enable_trigger=1
xdebug.profiler_output_dir=/debug
xdebug.var_display_max_depth=7
xdebug.remote_host=${CONTAINER_IP}
max_execution_time=600
EOF
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
exec "$@"
