#!/bin/sh

cat << EOF > /etc/msmtprc
host $SMTP_HOST
auto_from on
maildomain $SMTP_MAILDOMAIN
EOF

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
