#!/usr/bin/env php
<?php

if(isset($argv[1])){
    $dump = "{$argv[1]}";
    if(!file_exists($dump)){
        die("Error: could not find state: '$dump'.\n");
    }
}else{
    $states = trim(`ls -1t /state/*.tar 2> /dev/null`);
    if(!$states){
        die("Error: could not find any state dumps in /state.\n");
    }
    $states = explode("\n", $states);
    echo "Choose the number for the state you want to load (or 'Enter' for the most recent):\n";
    foreach($states as $n => $state){
        echo "[$n] " . basename($state) . "\n"; 
    }
    $key = readline();
    if($key == ''){
        $key = 0;
    }
    if(array_key_exists($key, $states)){
        $dump = $states[$key];
    }else{
        die("Error: '$key' was not an option.\n");
    }
}

$loadDir = tempnam('/tmp', 'civicrm_load_');
`rm $loadDir; mkdir $loadDir`;
echo "Opening $dump\n";
`tar -xf $dump -C $loadDir `;
$state = json_decode(file_get_contents("$loadDir/state.json"), 1);
foreach($state['databases'] as $name){
    foreach(['USER', 'PASS', 'HOST', 'PORT', 'NAME'] as $var){
        $$var = getenv(strtoupper($name) . '_DB_' . $var);
    }
    echo "Importing $name.sql into $NAME database\n";
    `mysql -p$PASS -u $USER -h $HOST -e "DROP DATABASE IF EXISTS $NAME; CREATE DATABASE $NAME"`;
    `mysql -p\$MYSQL_ROOT_PASSWORD -u root -h $HOST $NAME < $loadDir/$name.sql`;
}

foreach($state['directories'] as $name => $path){
    echo "Unpacking $name.tar database into $path\n";
    `tar -xf {$loadDir}/{$name}.tar -C $path`;
}

`rm -r $loadDir`;
`cv flush -T`;

$postLoadScripts = trim(`ls -1t /home/civicrm/postLoad/ 2> /dev/null`);
if($postLoadScripts){
    $postLoadScripts = explode("\n", $postLoadScripts);
    foreach($postLoadScripts as $script){
        echo "Running post load script '$script'\n";
        `/home/civicrm/postLoad/$script`; 
    }

    
}

