#!/usr/bin/env php
<?php

if (isset($argv[1])) {
    $dump = "{$argv[1]}";
    if (!file_exists($dump)) {
        die("Error: could not find state: '$dump'.\n");
    }
} else {
    $states = trim(`ls -1r /state/*.tar.gz 2> /dev/null`);
    if (!$states) {
        die("Error: could not find any state dumps in /state.\n");
    }
    $states = explode("\n", $states);
    echo "Choose the number for the state you want to load (or 'Enter' for the most recent):\n";
    foreach ($states as $n => $state) {
        echo "[$n] " . basename($state) . "\n";
    }
    $key = readline();
    if ($key == '') {
        $key = 0;
    }
    if (array_key_exists($key, $states)) {
        $dump = $states[$key];
    } else {
        die("Error: '$key' was not an option.\n");
    }
}

$loadDir = tempnam('/tmp', 'civicrm_load_');
`rm $loadDir; mkdir $loadDir`;
echo "Opening $dump\n";
`tar -xf $dump -C $loadDir `;
$state = json_decode(file_get_contents("$loadDir/state.json"), 1);
foreach ($state['databases'] as $name) {
    foreach (['USER', 'PASS', 'HOST', 'PORT', 'NAME'] as $var) {
        $$var = getenv(strtoupper($name) . '_DB_' . $var);
    }
    echo "Importing $name dump into $NAME database\n";
    `mysql -p$PASS -u $USER -h $HOST -e "DROP DATABASE IF EXISTS $NAME; CREATE DATABASE $NAME"`;
    `sed -E "/^\/\*\![[:digit:]]+ DEFINER/d" $loadDir/$name.sql | mysql -p$PASS -u $USER -h $HOST $NAME`;
}

foreach ($state['directories'] as $name => $path) {
    echo "Unpacking $name tar into $path\n";
    `tar -xf {$loadDir}/{$name}.tar.gz -C $path`;
}

`rm -r $loadDir`;
`cv flush -T`;

if (is_executable('/home/civicrm/postLoad')) {
    `/home/civicrm/postLoad`;
}
