#!/bin/bash
set -x

# Initialise CiviCRM and Backdrop ready for loading an existing state dump or a fresh installation. Destroys any existing data and files.
# Called automatically by civicrm-docker-install.

pushd /var/www/html

  chmod u+w .
  for FILE in settings.php civicrm.settings.php; do
    if test -f "$FILE"; then
      chmod u+w $FILE
    fi
    cp /usr/local/etc/civicrm/$FILE .
    chmod a-wx $FILE
  done
  rm -rf files
  mkdir files
  chmod u-w .

popd

mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "DROP DATABASE IF EXISTS $CIVICRM_DB_NAME; CREATE DATABASE $CIVICRM_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $BACKDROP_DB_HOST -e "DROP DATABASE IF EXISTS $BACKDROP_DB_NAME; CREATE DATABASE $BACKDROP_DB_NAME"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $CIVICRM_DB_HOST -e "GRANT ALL PRIVILEGES ON $CIVICRM_DB_NAME.* TO '$CIVICRM_DB_USER' IDENTIFIED BY '$CIVICRM_DB_PASS'"
mysql -p$MYSQL_ROOT_PASSWORD -u root -h $BACKDROP_DB_HOST -e "GRANT ALL PRIVILEGES ON $BACKDROP_DB_NAME.* TO '$BACKDROP_DB_USER' IDENTIFIED BY '$BACKDROP_DB_PASS'"

