#!/bin/bash
set -x

# Initialise CiviCRM and Backdrop ready for loading an existing state dump or a fresh installation. Destroys any existing data and files.
# Called automatically by civicrm-docker-install.

pushd /var/www/html

  chmod u+w .
  for FILE in settings.php civicrm.settings.php; do
    if test -f "$FILE"; then
      chmod u+w $FILE
    fi
    cp /usr/local/etc/civicrm/$FILE .
    chmod a-wx $FILE
  done
  chmod u-w .

popd
